package = "rsjson-lua"
lua = ">=5.1"

[description]
summary = "a json library for lua using serde-json"
maintainer = "benniekiss"
homepage = "https://github.com/benniekiss/rsjson-lua"
issues_url = "https://github.com/benniekiss/rsjson-lua/issues"
labels = ["json", "rust", "bindings"]
license = "MIT"

[source]
url = "https://github.com/benniekiss/$(PACKAGE)/archive/refs/tags/$(REF).zip"
dev = "git+https://github.com/benniekiss/$(PACKAGE)"

[build]
type = "rust-mlua"
default_features = false
features = ["module"]

[build.modules]
"rsjson_lua" = "rsjson_lua"

[build.include]
"lua/rsjson.lua" = "rsjson.lua"

[test]
type = "busted"

[test_dependencies]
busted = "2.3.0-1"
luacov = "0.17.0-1"
luamark = "1.1.1-1"
lpeg = "1.1.0-2"
dkjson = "2.8-2"
lua-cjson = "2.1.0-1"
rapidjson = "0.7.2-1"
