package = "rsjson"
lua = ">=5.1"

[description]
summary = "Lua bindings for serde-json"
maintainer = "benniekiss"
homepage = "https://github.com/benniekiss/rsjson"
issues_url = "https://github.com/benniekiss/rsjson/issues"
labels = ["json", "rust", "bindings"]
license = "MIT"

[source]
url = "https://github.com/benniekiss/$(PACKAGE)/archive/refs/tags/$(REF).zip"
dev = "git+https://github.com/benniekiss/$(PACKAGE)"

[build]
type = "rust-mlua"
default_features = false
features = ["module"]

[build.modules]
"serde_json" = "rsjson_lua"

[build.include]
"lua/rsjson.lua" = "rsjson.lua"

[test]
type = "busted"

[test_dependencies]
busted = "2.3.0-1"
luacov = "0.17.0-1"
